[versions]
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
jetbrains-compose = "1.10.0"
tiamat = "2.2.0"
leviathan = "3.1.0"

[libraries]
kotlin-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "jetbrains-compose" }
tiamat-core = { module = "io.github.composegears:tiamat", version.ref = "tiamat" }
tiamat-destinations = { module = "io.github.composegears:tiamat-destinations", version.ref = "tiamat" }
leviathan = { module = "io.github.composegears:leviathan", version.ref = "leviathan" }
leviathan-compose = { module = "io.github.composegears:leviathan-compose", version.ref = "leviathan" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
tiamat-destinations = { id = "io.github.composegears.tiamat.destinations.compiler", version.ref = "tiamat" }